[mypy]
ignore_missing_imports = False

[mypy-convertdate]
ignore_missing_imports = True

[mypy-convertdate.*]
ignore_missing_imports = True

[mypy-jose]
ignore_missing_imports = True

[mypy-jose.*]
ignore_missing_imports = True

[mypy-passlib]
ignore_missing_imports = True

[mypy-passlib.*]
ignore_missing_imports = True
