FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip \
 && pip install --default-timeout=100 --no-cache-dir -r requirements.txt

COPY . .

ENV DATABASE_URL=sqlite:///./calendar_test_bootstrap.db

CMD ["pytest", "-v"]
